# Generated by Django 4.1.3 on 2023-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.CharField(choices=[('Vengara', 'Vengara'), ('Kottakkal', 'Kottakkal'), ('Perithalmanna', 'Perithalmanna'), ('Edappal', 'Edappal'), ('Manjeri', 'Manjeri'), ('Aluva', 'Aluva'), ('Kochi', 'Kochi'), ('Edapallly', 'Edapallly'), ('Paravur', 'Paravur'), ('Angamaly', 'Angamaly'), ('Mavoor', 'Mavoor'), ('Mukkam', 'Mukkam'), ('Koyilandi', 'Koyilandi'), ('Ramanattukara', 'Ramanattukara'), ('Feroke', 'Feroke'), ('Mananthavady', 'Mananthavady'), ('kalpetta', 'kalpetta'), ('Panamaram', 'Panamaram'), ('Chavakkad', 'Chavakkad'), ('Chalakkudy', 'Chalakkudy'), ('Irinjalakuda', 'Irinjalakuda')], max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(choices=[('malappuram', 'malappuram'), ('eranakkulam', 'eranakkulam'), ('kozhikode', 'kozhikode'), ('wayanad', 'wayanad'), ('thrissur', 'thrissur')], max_length=50),
        ),
    ]
