# Generated by Django 4.1.3 on 2023-02-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_district_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name': 'district', 'verbose_name_plural': 'Districts'},
        ),
    ]
